### ISSUE TITLE
Add short articles related to Java, C#, Go, C++(1 min read)

### ISSUE THREAD

**Issue by ZoranPandovski** [flashreads/blogs#83]
You can write :writing_hand: :book:  for the Java, C#, Golang, C++ topics that you want. It could be anything from data structures, how to use some library, to how to resolve some issues. The PR should follow the contribution guide and it shouldn't be too long(around 1min read time) :hourglass_flowing_sand: . 
>Note that you will need to add your name as an author and the blog will be published/shared with your attribution :heavy_check_mark: Also, please make sure that the content isn't copied from other websites .

**Comment by kushagra-shukla** [comment]
I will be writing about localization in java. `011-localization-internationalization.md` will be the file name as of now. I was wondering how do you ensure that nobody else uses 011 number because someone is working with this serial number.
Assign me :)

**Comment by kushagra-shukla** [comment]
Hey @ZoranPandovski ,
Can you please review and merge the PR and add the `hacktoberfest-accepted` label. 😄
